[window]
decorations = "None"
padding = { x = 8, y = 8 }
opacity = 0.85

[font]
normal = { family = "Ubuntu Mono", style = "Regular"}

[colors]
cursor = { text = "#0d0e0c", cursor = "#c8b6b8" }

[colors.primary]
background = "#FCFCFC"
foreground = "#5C6166"

[colors.normal]
black   = "#010101"
red     = "#e7666a"
green   = "#80ab24"
yellow  = "#eba54d"
blue    = "#4196df"
magenta = "#9870c3"
cyan    = "#51b891"
white   = "#c1c1c1"

[colors.bright]
black   = "#343434"
red     = "#ee9295"
green   = "#9fd32f"
yellow  = "#f0bc7b"
blue    = "#6daee6"
magenta = "#b294d2"
cyan    = "#75c7a8"
white   = "#dbdbdb"
