#!/bin/bash

BOLDGREEN="\e[1;32m"
ENDCOLOR="\e[0m"

USER="mart"
HOME="/home/$USER"
CFG="$HOME/.config"
DOTS="$HOME/git/dotfiles"

GITNAME="mart-mihkel"
GITMAIL="mart.mihkel.aun@gmail.com"

PKGS_CORE="base base-devel linux-lts linux-firmware amd-ucode grub mesa"
PKGS_COMMON="sudo man-db bash-completion git curl wget neovim vim tmux openssl openssh net-tools wpa_supplicant dhcpcd"
PKGS_EXTRA="neofetch ripgrep cmake make nvm gcc docker docker-compose docker-buildx containerd cloudflared"

if ! id -u aur > /dev/null 2>&1; then
    echo -e "\n${BOLDGREEN}[aur user setup]${ENDCOLOR}\n"

    useradd -m aur
    echo "aur   ALL = (root) NOPASSWD: /usr/bin/makepkg, /usr/bin/pacman" > /etc/sudoers.d/aur
fi

if ! command -v yay &> /dev/null; then
    echo -e "\n${BOLDGREEN}[aur helper setup]${ENDCOLOR}\n"

    pacman -S --needed --noconfirm base-devel git
    (cd /tmp && git clone https://aur.archlinux.org/yay-bin.git)
    su aur -c "(cd /tmp/yay-bin && makepkg -si)"
    rm -rf /tmp/yay-bin
fi

if [[ -z "$1" || "$1" == "core" ]]; then
    echo -e "\n${BOLDGREEN}[core]${ENDCOLOR}\n"

    su aur -c "yay -S --needed --noconfirm $PKGS_CORE"
fi

if [[ -z "$1" || "$1" == "common" ]]; then
    echo -e "\n${BOLDGREEN}[common]${ENDCOLOR}\n"

    su aur -c "yay -S --needed --noconfirm $PKGS_COMMON"

    usermod -a -G wheel "$USER"

    groupadd docker
    usermod -a -G docker "$USER"

    systemctl enable sshd.service

    git config --global user.name "$GITNAME"
    git config --global user.email "$GITMAIL"
    git config --global core.editor nvim
    git config --global init.defaultBranch master

    su "$USER" -c "
        ln -sf '$DOTS/nvim' '$CFG'
        ln -sf '$DOTS/bash/.bashrc' '$HOME/.bashrc'
        ln -sf '$DOTS/bash/.bash_profile' '$HOME/.bash_profile'
        ln -sf '$DOTS/tmux/.tmux.conf' '$HOME/.tmux.conf'
    "

    INPUTRC="/etc/inputrc"
    IGNORECASE="set completion-ignore-case on"
    if [[ ! -f "$INPUTRC" || $(grep -Fxq "$IGNORECASE" "$INPUTRC") ]] ; then
        echo $IGNORECASE >> $INPUTRC
    fi
fi

if [[ -z "$1" || "$1" == "extra" ]]; then
    echo -e "\n${BOLDGREEN}[extra]${ENDCOLOR}\n"

    su aur -c "yay -S --needed --noconfirm $PKGS_EXTRA"
fi
