$wp = ~/git/dotfiles/walls/snufkin.jpeg

$black   = rgb(010101)
$red     = rgb(e7666a)
$green   = rgb(80ab24)
$yellow  = rgb(eba54d)
$blue    = rgb(4196df)
$magenta = rgb(9870c3)
$cyan    = rgb(51b891)
$white   = rgb(c1c1c1)

general {
    ignore_empty_input = true
}

background {
    path = $wp
    blur_passes = 2
    blur_size = 4
}

input-field {
    outline_thickness = 1
    dots_center = true
    fade_on_empty = true
    placeholder_text = <i></i>
}
