monitor=,preferred,auto,1

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

windowrulev2 = idleinhibit fullscreen, class:^(*)$
windowrulev2 = idleinhibit fullscreen, title:^(*)$
windowrulev2 = idleinhibit fullscreen, fullscreen:1

source = land/theme.conf
source = land/input.conf
source = land/keymaps.conf

exec-once = hyprpaper
exec-once = hypridle
