$wp = ~/git/dotfiles/walls/snufkin.jpeg

general {
    ignore_empty_input = true
    immediate_render = true
    no_fade_out = true
    no_fade_in = true
}

background {
    path = $wp
    blur_passes = 2
    blur_size = 4
}

input-field {
    rounding = 0
    dots_center = true
    outline_thickness = 1
    inner_color = rgb(fbfbfb)
    placeholder_text =
    fail_text =
}
