monitor=,preferred,auto,1

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

windowrulev2 = idleinhibit fullscreen, class:^(*)$
windowrulev2 = idleinhibit fullscreen, title:^(*)$
windowrulev2 = idleinhibit fullscreen, fullscreen:1

input {
    kb_layout = ee
    repeat_rate = 32
    repeat_delay = 256
    follow_mouse = 1
    sensitivity = 0

    touchpad {
        natural_scroll = false
    }
}

source = land/keymaps.conf
source = land/theme.conf

exec-once = hyprpaper
exec-once = hypridle
