#!/bin/bash

BOLDGREEN="\e[1;32m"
ENDCOLOR="\e[0m"

USER="mart"
HOME="/home/$USER"
CONF="$HOME/.config"
DOTS="$HOME/.dots/arch"

GITNAME="mart-mihkel"
GITMAIL="mart.mihkel.aun@gmail.com"

PKGS_CORE="base base-devel linux-lts linux-firmware intel-ucode grub"
PKGS_COMMON="sudo man-db bash-completion git curl wget neovim vim tmux openssl openssh networkmanager intel-undervolt auto-cpufreq wol"
PKGS_EXTRA="neofetch ripgrep python cmake make nvm gcc r docker docker-compose docker-buildx containerd unzip zip cloudflared"
PKGS_WAYLAND="hyprland hypridle hyprlock hyprpaper greetd waybar wofi dunst polkit-kde-agent alacritty grim slurp wofi-emoji xdg-desktop-portal-hyprland xwaylandvideobridge"
PKGS_HARDWARE="pamixer pipewire pipewire-alsa pipewire-pulse wireplumber bluez bluez-utils ccid pcsclite gammastep brightnessctl"
PKGS_DESKTOP="noto-fonts-emoji noto-fonts-cjk ttf-ubuntu-mono-nerd firefox slack-desktop qdigidoc4 discord"

if ! id -u aur > /dev/null 2>&1; then
    echo -e "\n${BOLDGREEN}[aur user setup]${ENDCOLOR}\n"

    useradd -m aur
    echo "aur   ALL = (root) NOPASSWD: /usr/bin/makepkg, /usr/bin/pacman" > /etc/sudoers.d/aur
fi

if ! command -v yay &> /dev/null; then
    echo -e "\n${BOLDGREEN}[aur helper setup]${ENDCOLOR}\n"

    pacman -S --needed --noconfirm base-devel git
    (cd /tmp && git clone https://aur.archlinux.org/yay-bin.git)
    su aur -c "(cd /tmp/yay-bin && makepkg -si)"
    rm -rf /tmp/yay-bin
fi

echo -e "\n${BOLDGREEN}[install]${ENDCOLOR}\n"

su aur -c "yay -S --needed --noconfirm $PKGS_CORE $PKGS_COMMON $PKGS_EXTRA $PKGS_WAYLAND $PKGS_HARDWARE $PKGS_DESKTOP"

groupadd docker
groupadd network

usermod -a -G wheel "$USER"
usermod -a -G docker "$USER"
usermod -a -G network "$USER"

systemctl enable pcscd.service
systemctl enable docker.service
systemctl enable greetd.service
systemctl enable NetworkManager

git config --global user.name "$GITNAME"
git config --global user.email "$GITMAIL"
git config --global core.editor vim

ln -sf "$DOTS/greetd/config.toml" /etc/greetd/config.toml
su "$USER" -c "
    ln -sf '$DOTS/tmux/.tmux.conf' '$HOME/.tmux.conf'
    ln -sf '$DOTS/bash/.bashrc' '$HOME/.bashrc'
    ln -sf '$DOTS/alacritty' '$CONF'
    ln -sf '$DOTS/waybar' '$CONF'
    ln -sf '$DOTS/dunst' '$CONF'
    ln -sf '$DOTS/nvim' '$CONF'
    ln -sf '$DOTS/wofi' '$CONF'
    ln -sf '$DOTS/hypr' '$CONF'
"
