$black   = rgb(010101)
$red     = rgb(e7666a)
$green   = rgb(80ab24)
$yellow  = rgb(eba54d)
$blue    = rgb(4196df)
$magenta = rgb(9870c3)
$cyan    = rgb(51b891)
$white   = rgb(c1c1c1)

general {
    gaps_in = 4
    gaps_out = 8
    border_size = 1
    resize_on_border = true
    allow_tearing = false
    layout = dwindle

    col.active_border = $black
    col.inactive_border = rgba(00000000)
}

decoration {
    rounding = 0
    active_opacity = 1.0
    inactive_opacity = 1.0
    drop_shadow = false

    blur {
        enabled = false
    }
}

animations {
    enabled = false
}

dwindle {
    pseudotile = true
    preserve_split = true
    no_gaps_when_only = true
}

master {
    new_status = master
}
