- hosts: localhost
  become: true
  tasks:

  - name: include vars
    include_vars:
      file: vars.yml

  - name: install packages
    pacman:
      name:
      - noto-fonts-emoji
      - noto-fonts-cjk
      - fontconfig
      - alacritty
      - firefox
      - ripgrep
      - neovim
      - meson
      - ninja
      - cmake
      - make
      - gcc

  - name: install rust
    become_user: "{{ user }}"
    shell:
      cmd: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      creates: "{{ home }}/.rustup"

  - name: install node version manager
    become_user: "{{ user }}"
    shell:
      cmd: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.0/install.sh | bash
      creates: "{{ home }}/.nvm"

  - name: install node
    shell:
      cmd: "source {{ home }}/.nvm/nvm.sh && nvm install 22"
      creates: "{{ home }}/.nvm/alias"

  - name: install ubuntu mono nerd font
    become_user: "{{ user }}"
    shell: "{{ item }}"
    loop:
      - "mkdir -p {{ home }}/.local/share/fonts"
      - "cp {{ dotfiles }}/fonts/UbuntuMonoNerdFont-Regular.ttf {{ home }}/.local/share/fonts/UbuntuMonoNerdFont-Regular.ttf"
      - "fc-cache -f -v"

  - name: symlink configs
    file:
      path: "{{ item.path }}"
      src: "{{ item.src }}"
      state: link
      force: yes
    loop:
      - { path: "{{ config }}/nvim", src: "{{ dotfiles }}/nvim" }
      - { path: "{{ config }}/alacritty", src: "{{ dotfiles }}/alacritty" }
