- hosts: localhost
  become: true
  tasks:

  - name: include vars
    include_vars:
      file: vars.yml

  - name: install software
    pacman:
      name:
      - networkmanager
      - bluez-utils
      - bluez
      - pulseaudio
      - pulseaudio-alsa
      - pulseaudio-bluetooth
      - pamixer
      - openssl
      - openssh
      - docker-compose
      - docker-buildx
      - docker
      - containerd
      - fontconfig
      - bash-completion
      - curl
      - sudo
      - man
      - git
      - vim

  - name: git config
    become_user: "{{ user }}"
    community.general.git_config:
      name: "{{ item.name }}"
      value: "{{ item.value }}"
      scope: global
    loop:
      - { name: user.name, value: mart-mihkel }
      - { name: user.email, value: mart.mihkel.aun@gmail.com }
      - { name: core.editor, value: vim }

  - name: create docker group
    group:
      name: docker
      state: present

  - name: add user to docker group
    user:
      name: "{{ user }}"
      groups: docker
      append: true

  - name: enable services
    systemd_service:
      enabled: true
      state: started
      name: "{{ item }}"
    loop:
      - NetworkManager
      - bluetooth
      - docker

  - name: create dirs
    become_user: "{{ user }}"
    file:
      path: "{{ config }}"
      state: directory
    loop:
      - "{{ config }}"
      - "{{ home }}/.local/bin"

  - name: symlink bash config
    file:
      path: "{{ item.path }}"
      src: "{{ item.src }}"
      state: link
      force: yes
    loop:
      - { path: "{{ home }}/.bashrc", src: "{{ home }}/dotfiles/.bashrc"}
      - { path: "{{ home }}/.bash_profile", src: "{{ home }}/dotfiles/.bash_profile"}
