- hosts: localhost
  become: true
  tasks:

  - name: include vars
    include_vars:
      file: vars.yml

  - name: install dependencies
    pacman:
      name:
      - gtk3
      - pango
      - gdk-pixbuf2
      - libdbusmenu-gtk3
      - cairo
      - glib2
      - gcc-libs
      - glibc

  - name: build eww
    become_user: "{{ user }}"
    shell:
      chdir: "{{ home }}/dotfiles/eww/eww"
      cmd: "{{ home }}/.cargo/bin/cargo build --release --no-default-features --features=x11"

  - name: copy eww binary to cargo binaries
    shell: "cp {{ home }}/dotfiles/eww/eww/target/release/eww {{ home }}/.cargo/bin/eww"

  - name: symlink config
    file:
      path: "{{ config }}/eww"
      src: "{{ home }}/dotfiles/eww"
      state: link
