- hosts: localhost
  become: true
  tasks:

  - name: include vars
    include_vars:
      file: vars.yml

  - name: install dependencies
    pacman:
      name:
      - hyprland

  - name: install additional pacages
    pacman:
      name:
      - picom
      - feh
      - rofi
      - rofimoji
      - xdotool


  - name: symlink configs
    file:
      path: "{{ item.path }}"
      src: "{{ item.src }}"
      state: link
      force: yes
    loop:
      - { path: "{{ config }}/xmonad", src: "{{ dotfiles }}/xmonad" }
      - { path: "{{ config }}/picom", src: "{{ dotfiles }}/picom" }
      - { path: "{{ config }}/rofi", src: "{{ dotfiles }}/rofi" }
      - { path: "{{ home }}/.fehbg", src: "{{ dotfiles }}/.fehbg" }
      - { path: "{{ home }}/.xinitrc", src: "{{ dotfiles }}/.xinitrc" }
