- hosts: localhost
  become: true
  tasks:

  - name: include vars
    include_vars:
      file: vars.yml

  - name: pacman sync
    pacman:
      name:
      - polkit-kde-agent
      - hyprland
      - hypridle
      - hyprlock
      - hyprpaper
      - cliphist
      - swaync
      - waybar
      - wofi

  - name: symlink configs
    file:
      path: "{{ item.path }}"
      src: "{{ item.src }}"
      state: link
      force: yes
    loop:
      - { path: "{{ config }}/waybar", src: "{{ dotfiles }}/waybar" }
      - { path: "{{ config }}/wofi", src: "{{ dotfiles }}/wofi" }
      - { path: "{{ config }}/hypr", src: "{{ dotfiles }}/hypr" }
