- hosts: localhost
  become: true
  tasks:

  - name: include vars
    include_vars:
      file: vars.yml

  - name: pacman sync
    pacman:
      name:
      - hyprland
      - hypridle
      - hyprlock
      - hyprpaper
      - rofi-wayland

  - name: symlink configs
    file:
      path: "{{ item.path }}"
      src: "{{ item.src }}"
      state: link
      force: yes
    loop:
      - { path: "{{ config }}/hypr", src: "{{ dotfiles }}/hypr" }
      - { path: "{{ config }}/rofi", src: "{{ dotfiles }}/rofi" }
