- hosts: localhost
  become: true
  tasks:

  - name: include vars
    include_vars:
      file: vars.yml

  - name: install neovim
    pacman:
      name: neovim

  - name: symlink config
    file:
      path: "{{ config }}/nvim"
      src: "{{ home }}/dotfiles/nvim"
      state: link
