- hosts: localhost
  become: true
  tasks:

  - name: include vars
    include_vars:
      file: vars.yml

  - name: install dependencies
    pacman:
      name:
      - rofi
      - rofimoji
      - xdotool

  - name: symlink configs
    file:
      path: "{{ item.path }}"
      src: "{{ item.src }}"
      state: link
      force: yes
    loop:
      - { path: "{{ config }}/rofi", src: "{{ home }}/dotfiles/rofi"}
