- hosts: localhost
  become: true
  tasks:

  - name: include vars
    include_vars:
      file: vars.yml

  - name: install dependencies
    pacman:
      name:
      - xorg-server
      - xorg-apps
      - xorg-xinit
      - xorg-xmessage
      - libx11
      - libxft
      - libxinerama
      - libxrandr
      - libxss
      - pkgconf

  - name: install additional pacages
    pacman:
      name:
      - picom
      - feh
      - rofi
      - rofimoji
      - xdotool

  - name: build xmonad
    become_user: "{{ user }}"
    shell:
      chdir: "{{ dotfiles }}/xmonad"
      cmd: stack install
    environment:
        PATH: "{{ home }}/.ghcup/bin:{{ ansible_env.PATH }}"

  - name: symlink configs
    file:
      path: "{{ item.path }}"
      src: "{{ item.src }}"
      state: link
      force: yes
    loop:
      - { path: "{{ config }}/xmonad", src: "{{ dotfiles }}/xmonad" }
      - { path: "{{ config }}/picom", src: "{{ dotfiles }}/picom" }
      - { path: "{{ config }}/rofi", src: "{{ dotfiles }}/rofi" }
      - { path: "{{ home }}/.fehbg", src: "{{ dotfiles }}/.fehbg" }
      - { path: "{{ home }}/.xinitrc", src: "{{ dotfiles }}/.xinitrc" }
